image: ruby:3.1.2-bullseye

variables:
  ASDF_DIR: "${CI_PROJECT_DIR}/.asdf"
  ASDF_DATA_DIR: "${CI_PROJECT_DIR}/.asdf"
  ASDF_VERSION: "0.10.0"
  BUNDLE_APP_CONFIG: "${CI_PROJECT_DIR}/.bundle"
  GEM_HOME: "${CI_PROJECT_DIR}/.gem"

cache:
  - key:
      prefix: rubygems
      files:
        - Gemfile.lock
    paths:
      - .gem
      - vendor
  - key:
      prefix: node_modules
      files:
        - yarn.lock
    paths:
      - node_modules
  - key:
      prefix: asdf
      files:
        - .tool-versions
    when: "always"
    paths:
      - .asdf
  - key: default
    paths:
      - .bridgetown-cache
      - .bundle

test:
  stage: test
  script:
    - source .gitlab/ci.sh
    - ci_section asdf ./.gitlab/asdf.sh && source .asdf/asdf.sh
    - ci_section setup ./bin/setup
    - |
      ci_start tool-versions
      echo "versions from .tool-versions:" && cat .tool-versions
      echo "runtime versions:"
      echo "node" $(node --version)
      echo "yarn" $(yarn --version)
      ruby --version
      echo "gem" $(gem --version)
      bundler --version ; bundler config
      ci_end tool-versions
    - ci_section ci ./bin/ci
    - ci_section deploy ./bin/deploy
