image: ruby:3.1.2-bullseye

variables:
  ASDF_DIR: "${CI_PROJECT_DIR}/.asdf"
  ASDF_DATA_DIR: "${CI_PROJECT_DIR}/.asdf"
  ASDF_VERSION: "0.10.0"
  BUNDLE_APP_CONFIG: "${CI_PROJECT_DIR}/.bundle"

cache:
  paths:
    - .asdf
    - .bridgetown-cache
    - .bundle
    - node_modules
    - vendor

before_script:
  - source .gitlab/ci.sh
  - ci_section asdf ./.gitlab/asdf.sh && source .asdf/asdf.sh

setup:
  stage: build
  script:
    - ci_section setup ./bin/setup

test:
  stage: test
  needs:
    - job: setup
      artifacts: true
  script:
    - |
      ci_start tool-versions
      echo ".tool-versions" && cat .tool-versions
      echo "node" $(node --version)
      echo "yarn" $(yarn --version)
      ruby --version
      echo "gem" $(gem --version)
      bundler --version ; bundler config
      ci_end tool-versions
    - ci_section ci ./bin/ci
    - ci_section deploy ./bin/deploy
