# Welcome to Bridgetown!
#
# This config file is for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `bin/bridgetown start`. If you change this file, please restart the server process.
#
# For reloadable site metadata like title, SEO description, social media
# handles, etc., take a look at `src/_data/site_metadata.yml`
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

url: "https://agnevaitkeviciute.com"

permalink: pretty
template_engine: liquid

# Other options you might want to investigate:
#
# base_path: "/" # the subpath of your site, e.g. /blog. If you set this option,
# ensure you use the `relative_url` helper for all links and assets in your HTML.
# If you're using esbuild for frontend assets, edit `esbuild.config.js` to
# update `publicPath`.

timezone: Europe/Luxembourg
pagination:
  enabled: true

flickr_portfolio:
  api_key: ENV.FLICKR_API_KEY
  api_secret: ENV.FLICKR_API_SECRET
  user_id: ENV.FLICKR_USER_ID
